version: '3'
services:
  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - 8080:80
      - 8081:81
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./main:/var/www/app/public:ro
      - pma_data:/var/www/html:ro
    #environment:
    #  - NGINX_PORT=80

  app:
    restart: unless-stopped
    build:
      context: ./main
      dockerfile: Dockerfile
    volumes:
      - ./main:/var/www/app/public
    environment:
      DB_HOST: db
    #ports:
    #  - 8000:80
    depends_on:
      - db

  db:
    image: mariadb:10.6.15
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_gmc
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:5.2-fpm-alpine
    restart: unless-stopped
    #ports:
    #  - 8080:80
    volumes:
      - pma_data:/var/www/html
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
      
volumes:
  mysql_data:
  pma_data: